### PR TITLE
Fix for Could not find @ReactModule annotation issue

### PR DESCRIPTION
**Pull request by jdnichollsc**
To fix this issue https://github.com/mauritsd/react-native-dynamic-bundle/issues/4 for RN 0.58

Regards, Juan

### CODE REVIEW

**Comment by jdnichollsc** [comment]
ok, the issue must have been fixed for RN 0.58

**Comment by jdnichollsc** [comment]
@mauritsd can you accept this pull request?

**Comment by jdnichollsc** [comment]
@mauritsd thanks for your help! Can you publish that new version from npm please?

**Comment by itrcz** [comment]
upload to npm please ((

**Pull request merged**
